version: "3.8"

services:
    server:
        container_name: server_app
        build: ./server
        ports:
            - 3001:3001
        volumes:
            - type: bind
              source: ./server/src
              target: /src
              read_only: false

    client:
        container_name: client_app
        build: ./client
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./client/src
              target: /src
              read_only: false

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: mintgram
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
        driver: local
