version: "3.8"

services:
    mongodb:
        image: mongo:6.0 # Укажите желаемую версию MongoDB
        container_name: mongodb-container
        ports:
            - "27018:27017" # Проброс порта для подключения к MongoDB
        environment:
            MONGO_INITDB_ROOT_USERNAME: root # Имя пользователя администратора
            MONGO_INITDB_ROOT_PASSWORD: example # Пароль пользователя администратора
            MONGO_INITDB_DATABASE: mintgram # Название создаваемой базы данных
        volumes:
            - mongodb_data:/data/db # Хранение данных в volume для их сохранения при перезапуске контейнера

volumes:
    mongodb_data:
        driver: local
